### PR TITLE
Add gcxs to docs

### PR DESCRIPTION
**Pull request by daletovar**
- Makes gcxs public api
- adds docs
I think updating index.rst and roadmap.rst is appropriate.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
Doc build is failing with:

```
/home/vsts/work/1/s/sparse/_compressed/compressed.py:docstring of sparse.GCXS.reshape:5:Unexpected indentation.
```

Which means the 5th line in the docstring of `sparse.GCXS.reshape` is improperly indented.

**Comment by hameerabbasi** [comment]
Can you fix the doc linting issue and rebase on master.

**Comment by daletovar** [comment]
@hameerabbasi  Yes, sorry about the delays.

**Comment by hameerabbasi** [comment]
Thanks, @daletovar!

**Pull request merged**
