### PR TITLE
Update `sparse_finch` notebook and upgrade `finch-tensor`

### PR DESCRIPTION
**Pull request by mtsokol**
This PR upgrades `finch-tensor` to `0.2.1` and updates `sparse_finch.ipynb` to also include "Finch - Galley" configuration and Counting triangles example.

### CODE REVIEW

**Review by hameerabbasi — DISMISSED** [review]
LGTM, just the nit below.

**Comment by mtsokol** [comment]
We still need to wait for https://github.com/finch-tensor/finch-tensor-python/pull/79

**Comment by mtsokol** [comment]
@hameerabbasi Let's upgrade `finch-tensor` here also and skip https://github.com/pydata/sparse/pull/823. Here's no need to have it in a separate PR.

**Review by hameerabbasi — DISMISSED** [review]

**Comment by hameerabbasi** [comment]
Thanks for the update, @mtsokol!

**Comment by mtsokol** [comment]
@hameerabbasi I promise this is the last one 😅 Can you re-approve? Now it's all green!

**Review by hameerabbasi — APPROVED** [review]

**Comment by mtsokol** [comment]
Merged! I think we can cut first beta release!

**Pull request merged**
