### PR TITLE
BLD: Revert micromamba version to v2

### PR DESCRIPTION
**Pull request by mtsokol**
This PR reverts CI change introduced in #799.

### CODE REVIEW

**Review by hameerabbasi — APPROVED** [review]

**Comment by mtsokol** [comment]
I think we should merge it once windows job passes, so when https://github.com/mamba-org/setup-micromamba/issues/227 is fixed. WDYT?

**Comment by hameerabbasi** [comment]
> I think we should merge it once windows job passes, so when https://github.com/mamba-org/setup-micromamba/issues/227 is fixed. WDYT?

SGTM, can't merge it until CI passes anyway. So my recommendation would be to re-run the CI and then merge after a fix.

**Comment by mtsokol** [comment]
I think we can merge it - the bug was solved in mamba (failing job is unrelated I think)

**Comment by hameerabbasi** [comment]
Thanks, @mtsokol!

**Pull request merged**
