### PR TITLE
Add more lints to Ruff for better code quality.

### PR DESCRIPTION
**Pull request by hameerabbasi**
This PR also adds lints that check for NumPy 2.0 compatibility.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
@mtsokol Do you primarily work on Windows? If so, would it be possible for you to look into why this fails only on Windows?

**Comment by mtsokol** [comment]
> @mtsokol Do you primarily work on Windows? If so, would it be possible for you to look into why this fails only on Windows?

I only have macos machine unfortunately.

**Comment by mtsokol** [comment]
@hameerabbasi I have and idea what might be causing the failure. In `test_elemwise.py` (where tests are failing) there's a number of `.astype(np.int_)`. `np.int_` is an informal "default integer", which I think causes trouble here - on Windows it's 32bit but here for the sparse operation it stays as 64bit.

While working on NEP 52 there was even a discussion to remove `np.int_` and `np.uint` to enforce users to use sized aliases explicitly (e.g. `np.int64`) or c-like names (`np.long`). `np.int_` will get removed in a few releases: https://github.com/numpy/numpy/issues/24743

Maybe a solution would be to replace `.astype(np.int_)` in `test_elemwise.py` with `.astype(np.int64)` or `np.int32`?

**Comment by hameerabbasi** [comment]
> Maybe a solution would be to replace `.astype(np.int_)` in `test_elemwise.py` with `.astype(np.int64)` or `np.int32`? (it's only bitwise and bitshift tests that are failing)

That worked, thanks! I see you requested a review, I'll wait for that before merging.

**Review by mtsokol — APPROVED** [review]
LGTM!

**Pull request merged**
