### PR TITLE
Move back to Travis-CI

### PR DESCRIPTION
**Pull request by hameerabbasi**

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm curious, what was the motivation here?  Most people I've spoken to recently have had a nicer time with Circle-CI

**Comment by mrocklin** [comment]
In particular, I've found that the backlog on travis-ci can grow somewhat large, causing delays

**Comment by hameerabbasi** [comment]
Well, mainly the lack of a Travis-like "matrix" interface. I've gone through every possibility, and the only way to do something like that is to write separate CI code for every combination. I've asked around in the CircleCI Forum and other similar places as well.

**Comment by rgommers** [comment]
that's my experience too, TravisCI is still nicer if you have multiple builds.

**Pull request merged**
