### PR TITLE
Try to simplify the numba extension a little

### PR DESCRIPTION
**Pull request by eric-wieser**
Rather than using `contextlib.ExitStack` to manage our state, this uses LLVM basic blocks instead.

cc @stuartarchibald

---

Unfortunately this didn't appear to improve compile-time performance.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
CI fails with: `NameError: name 'lower_builtin' is not defined`.

**Comment by hameerabbasi** [comment]
Is this ready for review?

**Comment by eric-wieser** [comment]
> Is this ready for review?

Yeah, I think so. There are some open questions about `NativeValue.cleanup` that I was hoping to resolve here, but I'm realizing that that opens a can of worms that numba needs to look at - so I'll leave that to a follow-up.

**Comment by hameerabbasi** [comment]
Pinging @stuartarchibald for a review.

**Comment by hameerabbasi** [comment]
I'll wait a day or two for review before merging.

**Comment by hameerabbasi** [comment]
Whoops, forgot about this one. Thanks, @eric-wieser!

**Pull request merged**
