### PR TITLE
use static arrays for indexing

### PR DESCRIPTION
**Pull request by daletovar**
I've replaced the dynamic structures with static ones for GCXS indexing. This improves the speed pretty significantly (twice as fast in a number of cases). Also, even allocating extra space in arrays seems to outperform lists in terms of memory for the most part.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
Can you post benchmarks as well?

**Comment by hameerabbasi** [comment]
Also, we might want to hold off on merging this, Numba 0.52 introduces a number of improvements for typed lists, so switching to those might be worthwhile instead.

**Comment by daletovar** [comment]
Yeah, I can definitely add them to the ASV suite.

**Comment by hameerabbasi** [comment]
@daletovar I believe Numba 0.52 is out. Can we re-run the benchmarks on this with that version installed, against the old ones as well?

**Comment by daletovar** [comment]
Sure thing. I'll get right on that.

**Comment by hameerabbasi** [comment]
I ran the benchmarks on this a long time ago and this seemed to be obsolete. Closing for now.

**Pull request closed without merging**
