### PR TITLE
Add cmake and scikit-build

### PR DESCRIPTION
**Pull request by sayandip18**

### CODE REVIEW

**Comment by sayandip18** [comment]
@hameerabbasi Is there a way to get rid off these commits?

**Comment by H4R5H1T-007** [comment]
You can use `git reset --soft`. for more info checkout [here.](https://stackoverflow.com/a/5203843)

**Comment by sayandip18** [comment]
`git reset` will not work from my end since the branch vnext is probably merged with master, which is leading to the previous commits appearing here before mine.

**Comment by hameerabbasi** [comment]
> @hameerabbasi Is there a way to get rid off these commits?

If you merged with `master` they should be there.

**Comment by sayandip18** [comment]
I did not merge my branch with master.

**Comment by hameerabbasi** [comment]
You can possibly recreate the branch without deleting this one and cherry pick the commits you want.

**Comment by sayandip18** [comment]
Closing in favour of #485

**Pull request closed without merging**
