### PR TITLE
CI: Remove Python 3.8 and update miniconda

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @hameerabbasi,

This PR introduces CI changes that we did in `finch-tensor`.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
I would also update `pyproject.toml` to reflect that we no longer support Python 3.8.

**Comment by mtsokol** [comment]
> I would also update `pyproject.toml` to reflect that we no longer support Python 3.8.

Done!

**Review by hameerabbasi — APPROVED** [review]

**Comment by hameerabbasi** [comment]
Thanks for the updates, @mtsokol!

**Comment by hameerabbasi** [comment]
Seems like we need to change the required CI checks -- I'll d that later today.

**Pull request merged**
