### PR TITLE
added svg logo and logo-generating script

### PR DESCRIPTION
**Pull request by jamestwebber**
A PR to address #554. I may have gone a little bit crazy with it 😂 it was fun though

I wrote a script to generate an SVG logo with some random opacity, and modified the docs so that it looks right. That may seem crazy but the motivations were a) it was fun to do and b) there might be a lot of bike-shedding on this, and I'm not good enough with a Affinity Designer to make changes to an image quickly.

One question I had to decide: in the docs, the logo is shown on two different backgrounds. If I just used opacity then it looks very different, so I added white background squares. But this also looks a little odd on the blue background in the sidebar. The original logo didn't actually use opacity so it wasn't an issue there.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
> I wrote a script to generate an SVG logo with some random opacity, and modified the docs so that it looks right. That may seem crazy but the motivations were a) it was fun to do and b) there might be a lot of bike-shedding on this, and I'm not good enough with a Affinity Designer to make changes to an image quickly.

No bike shedding from my side -- I'd just fix the seed for reproducibility but other than that, we're good.

The test failures should be resolved when #555 is in.

**Comment by jamestwebber** [comment]
> No bike shedding from my side -- I'd just fix the seed for reproducibility but other than that, we're good.

Seed is set at 1 (0 didn't look random enough).

**Comment by hameerabbasi** [comment]
Could you merge/rebase `master` and we should be good to go.

**Comment by headtr1ck** [comment]
Currently on mobile so cannot really check much, but could you ensure that it also looks nice in dark mode?

**Comment by hameerabbasi** [comment]
I don't think we have a dark mode. It doesn't seem to come vanilla.

**Comment by jamestwebber** [comment]
Yeah when I view the docs after building locally I don't see an option for a dark mode. But I set the SVG background to black and took a screenshot::

**Comment by hameerabbasi** [comment]
My aesthetic sense is close to none, I'll let you be the judge of how that'll blend in.

**Comment by headtr1ck** [comment]
Yeah, maybe removing the white parts again and instead of using semi-transparent tiles, simply tiles with a lighter color?

**Comment by jamestwebber** [comment]
> Yeah, maybe removing the white parts again and instead of using semi-transparent tiles, simply tiles with a lighter color?

This does look pretty sweet on a dark background, but IMO it looks worse on the blue background of the docs page sidebar. Given that there isn't _actually_ a dark mode for the docs, I'm inclined to keep it with the white background.

Screen Shot 2022-08-17 at 18 58 36
Screen Shot 2022-08-17 at 18 58 50

**Comment by headtr1ck** [comment]
Maybe having two versions is also ok?
Alternatively, you can use CSS to change the color of the background to/from transparent to white?

**Comment by headtr1ck** [comment]
I have noticed that you removed the spacing between the sides.
Maybe it was too large in the initial version but I think no spacing is confusing, at least for the cube-2D intersection.

**Comment by jamestwebber** [comment]
Okay this is why I made the script 😂 I don't really have time to make additional tweaks but happy for you to play with it more.

**Comment by hameerabbasi** [comment]
Merging as-is for now... -- Thanks, @jamestwebber!-

**Pull request merged**
