### PR TITLE
Slicing and advanced indexing for DOK

### LINKED ISSUE #298: Support for DOK slicing and advanced indexing
Since the DOK array is versatile applicable I use them frequently in my projects. I needed support for slicing and advanced indexing and implemented it myself, see [gist](https://gist.github.com/stschroe/7c4660774835258c06b2be968eb49204#file-sparse_dok_indexer-py). 

The indexing supports slicing, advanced (fancy) indexing and as I need it most of the time "array indexing". This is a fast version for advanced indexing. Only vectors (1d sequences) are accepted for indexing. The getitem  method always returns dense ndarrays in contrast to normal advanced indexing of sparse arrays which create new copies of sparse arrays. The setitem method allows only vectors and scalars as values. This allows fast calculations over ndarray methods without the expensive creation of temporary sparse arrays between operations. This is of course only useful for small vectors, which fit easily in to memory.

If there is interest in adding this to pydata.sparse, I could help. But as I have never contributed to any open project, I have no idea if I could handle the necessary amount of work.

### PR DESCRIPTION
**Pull request by sayandip18**
Fixes #298

### CODE REVIEW

**Review by hameerabbasi — COMMENTED** [review]
Can we integrate this into the `DOK` type? I see some monkeypatching going on.

**Comment by sayandip18** [comment]
> Can we integrate this into the `DOK` type?

Do you mean including `vix` as a function in `DOK`?

**Comment by hameerabbasi** [comment]
> Do you mean including `vix` as a function in `DOK`?

I mean as an property.

**Comment by sayandip18** [comment]
Calling the function `add_vector_indexer_to_sparse_dok()` essentially does that. Maybe we can import and call the function in `_dok.py` which will give us the desired behaviour.

**Comment by hameerabbasi** [comment]
> Calling the function `add_vector_indexer_to_sparse_dok()` essentially does that. Maybe we can import and call the function in `_dok.py` which will give us the desired behaviour.

I'd prefer for `vix` to be directly added to all `DOK` objects.

**Comment by hameerabbasi** [comment]
@sayandip18 Do you plan to continue this?

**Pull request closed without merging**
