### PR TITLE
__array_function__ test coverage; numpy 1.17; result_type()

### PR DESCRIPTION
**Pull request by crusaderky**
- Support for numpy 1.17 (it's already what's used in CI today)
- Implement sparse.result_type + unit tests
- Refactor environment variables and other switches into sparse.settings
- Add unit tests for mixed numpy+sparse inputs to ``__array_function__``, with different permutations

### CODE REVIEW

**Comment by hameerabbasi** [comment]
I added a nice test for NEP-18 here: dask/dask#4675. Would you care to copy that one, as it tests the protocol?

**Comment by crusaderky** [comment]
@hameerabbasi done

**Comment by hameerabbasi** [comment]
Can you change the implementation of result_type to the following:

`return np.result_type(*(x.dtype if isinstance(x, SparseArray) else x for x in args)`

And move it to common.py?

**Comment by crusaderky** [comment]
All done, see if you like it

**Pull request merged**
