### PR TITLE
ENH: implement any and all functions

### LINKED ISSUE #173: Add any and all methods.
@stsievert Willing to take a crack at this? It's mostly docs/tests/copy-paste with a one-line implementation and can be easily copied from `min` or `max`:

https://github.com/pydata/sparse/blob/6210da31b9fc63c01b083c121421f335d73a580d/sparse/coo/core.py#L692-L939

### PR DESCRIPTION
**Pull request by stsievert**
This PR closes #173 and adds `any` and `all` methods to `COO`.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
Oh. Apparently you're using an old NumPy version... The docstrings need to be produced with newer versions to pass the tests, unfortunately. (1.14.0 or newer I think).

**Comment by hameerabbasi** [comment]
@stsievert Are you still interested in working on this? If not, is it okay if I pushed to your branch? You'd still be listed as the author of the commit.

**Comment by stsievert** [comment]
> is it okay if I pushed to your branch?

That's fine by me.

**Comment by hameerabbasi** [comment]
It seems like NumPy 1.15 changed the docstrings for bool arrays, omitting the dtype. For the tests to pass both locally and in Travis, I needed to skip these doctests.

**Pull request merged**
