### PR TITLE
add benchmarks

### PR DESCRIPTION
**Pull request by daletovar**
Here I've added asv benchmarks for GCXS. I also made a couple of changes to COO.

### CODE REVIEW

**Comment by daletovar** [comment]
@hameerabbasi, does this look okay to you?

**Comment by hameerabbasi** [comment]
Thanks. Could you run the benchmarks and post a reference? If that works, I'll merge tomorrow.

**Comment by daletovar** [comment]
Hey @hameerabbasi, sorry I missed this. Should I just post the results here in the thread?

**Comment by hameerabbasi** [comment]
@daletovar Yes. Probably my fault, forgot to tag you, but it isn't commonplace on the author's PR.

**Comment by daletovar** [comment]
```
[  0.00%] · For sparse commit bab39b1e <asv>:
[  0.00%] ·· Benchmarking conda-py3.8
[  1.92%] ··· Running (benchmark_coo.ElemwiseBroadcastingSuite.time_add--)..........
[ 21.15%] ··· Running (benchmark_gcxs.ElemwiseBroadcastingSuite.time_add--).........
[ 38.46%] ··· Running (benchmark_gcxs.MatrixMultiplySuite.time_matmul--)...
[ 44.23%] ··· Running (benchmark_tensordot.TensordotSuiteSparseDense.time_dense--)..
[ 48.08%] ··· Running (benchmark_tensordot.TensordotSuiteSparseSparse.time_dense--)..
[ 51.92%] ··· benchmark_coo.ElemwiseBroadcastingSuite.time_add                         6.23±0.2ms
[ 53.85%] ··· benchmark_coo.ElemwiseBroadcastingSuite.time_mul                           822±40μs
[ 55.77%] ··· benchmark_coo.ElemwiseSuite.time_add                                    7.65±0.05ms
[ 57.69%] ··· benchmark_coo.ElemwiseSuite.time_mul                                    2.28±0.02ms
[ 59.62%] ··· benchmark_coo.IndexingSuite.time_index_fancy                            2.17±0.01ms
[ 61.54%] ··· benchmark_coo.IndexingSuite.time_index_scalar                              62.7±1μs
[ 63.46%] ··· benchmark_coo.IndexingSuite.time_index_slice                                510±2μs
[ 65.38%] ··· benchmark_coo.IndexingSuite.time_index_slice2                               829±3μs
[ 67.31%] ··· benchmark_coo.IndexingSuite.time_index_slice3                              754±10μs
[ 69.23%] ··· benchmark_coo.MatrixMultiplySuite.time_matmul                              573±10μs
[ 71.15%] ··· benchmark_gcxs.ElemwiseBroadcastingSuite.time_add                        7.48±0.1ms
[ 73.08%] ··· benchmark_gcxs.ElemwiseBroadcastingSuite.time_mul                       2.23±0.05ms
[ 75.00%] ··· benchmark_gcxs.ElemwiseSuite.time_add                                    12.2±0.1ms
[ 76.92%] ··· benchmark_gcxs.ElemwiseSuite.time_mul                                   6.88±0.02ms
[ 78.85%] ··· benchmark_gcxs.IndexingSuite.time_index_fancy                           2.92±0.01ms
[ 80.77%] ··· benchmark_gcxs.IndexingSuite.time_index_scalar                              433±4μs
[ 82.69%] ··· benchmark_gcxs.IndexingSuite.time_index_slice                           2.85±0.02ms
[ 84.62%] ··· benchmark_gcxs.IndexingSuite.time_index_slice2                          1.93±0.01ms
[ 86.54%] ··· benchmark_gcxs.IndexingSuite.time_index_slice3                          1.54±0.02ms
[ 88.46%] ··· benchmark_gcxs.MatrixMultiplySuite.time_matmul                              791±3μs
[ 90.38%] ··· benchmark_tensordot.TensordotSuiteDenseSparse.time_dense                   390±20ms
[ 92.31%] ··· benchmark_tensordot.TensordotSuiteDenseSparse.time_sparse                  376±10ms
[ 94.23%] ··· benchmark_tensordot.TensordotSuiteSparseDense.time_dense                    303±2ms
[ 96.15%] ··· benchmark_tensordot.TensordotSuiteSparseDense.time_sparse                   305±2ms
[ 98.08%] ··· benchmark_tensordot.TensordotSuiteSparseSparse.time_dense                   197±2ms
[100.00%] ··· benchmark_tensordot.TensordotSuiteSparseSparse.time_sparse                  200±1ms
```

**Pull request merged**
