### PR TITLE
Improve CI and packaging

### PR DESCRIPTION
**Pull request by hameerabbasi**
Partial fix for #99

### CODE REVIEW

**Comment by hameerabbasi** [comment]
@mrocklin I don't have access to the Pydata repo, so I can't create a codecov page for this. Would you be so kind?

**Comment by mrocklin** [comment]
> I don't have access to the Pydata repo, so I can't create a codecov page for this

I'm not sure I understand.  I may not have gone through this particular process before.  Can I ask you to give more details about what you'd like done?

**Comment by hameerabbasi** [comment]
Thanks for doing this, it'd be great if:

- You added me to admins for Travis
- You created an account on [codecov.io](https://codecov.io).
- You added the PyData repo to this.
- Made me an admin.

**Comment by mrocklin** [comment]
I've connected this repository to codecov.io and sent you a secret by e-mail.  I don't think there are any additional permissions you need to codecov or travis-ci other than github permissions.  Please let me know if there is further work to do here.

**Pull request merged**
