### PR TITLE
[WIP] Add a custom-coded dot product.

### PR DESCRIPTION
**Pull request by hameerabbasi**
Add a custom-coded dot product. Done:

- [x] `COO`-`COO`
- [x] `COO`-`ndarray`
- [x] `ndarray`-`COO`
- [x] Documentation

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for putting this in @hameerabbasi! I have been trying it out with https://github.com/scopatz/minimal-failing-sparse-dot and it seems to fail no matter if it is a `COO @ COO` or `ndarray @ COO` or `COO @ ndarray`. At least in Jupyter, the kernel dies.

**Comment by hameerabbasi** [comment]
@scopatz Thanks for the message. From the traceback you showed, you're still using the code from `master`, not this branch, since this branch hasn't been merged yet. The code in the traceback has been removed from this branch.

You'll need to clone the `custom-dot` branch in my repo and run `pip install` on it.

**Comment by scopatz** [comment]
Oh I haven't pushed an updated minimal example repo. I have just playing around with a local install of this branch.

**Comment by scopatz** [comment]
I am on `0.5.0+16.gdcc437c` locally.

**Comment by scopatz** [comment]
Hmm actually, that repo might be bad example because in the worst case it could end up with the dot product having a `nnz == 674916321618`, which is about 643 GB for float64.

**Comment by scopatz** [comment]
Yeah, I agree.  That is a breaking case, so please ignore.

**Pull request merged**
