### PR TITLE
ci: Merge MLIR Backend

### PR DESCRIPTION
**Pull request by hameerabbasi**
## What type of PR is this? (check all applicable)

- [ ] 💾 Refactor
- [ ] 🪄 Feature
- [ ] 🐞 Bug Fix
- [ ] 🔧 Optimization
- [ ] 📚 Documentation
- [x] 🧪 Test
- [x] 🛠️ Other

## Checklist

- [x] Code follows style guide
- [x] Tests added
- [x] Documented the changes

***

## Please explain your changes below.
* Merge MLIR backend tests to all others
* Add coverage testing for MLIR Backend
* Use `micromamba-action`.

### CODE REVIEW

**Comment by hameerabbasi** [comment]
Blocked due to scipy/scipy#21442, workaround in #757.

**Comment by mtsokol** [comment]
LGTM, but let's merge https://github.com/pydata/sparse/pull/757 first and see CI green.

**Comment by hameerabbasi** [comment]
> LGTM, but let's merge #757 first and see CI green.

I cherry-picked the changes to not block this PR.

**Review by mtsokol — COMMENTED** [review]
Thanks! LGTM!

**Pull request merged**
